//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alver.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Motto { get; set; }
        public string Manager { get; set; }
        public string ManagerPhone { get; set; }
        public string Accountant { get; set; }
        public string AccountantPhone { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public Nullable<int> LogoId { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<bool> PROTECTED { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
