//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alver.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> ExchangeDate { get; set; }
        public string Direction { get; set; }
        public Nullable<int> BaseCurrencyId { get; set; }
        public Nullable<decimal> BaseAmount { get; set; }
        public Nullable<int> SubCurrencyId { get; set; }
        public string Factor { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> SubAmount { get; set; }
        public Nullable<decimal> RoundAmount { get; set; }
        public string Declaration { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<bool> PROTECTED { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
