//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alver.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<System.DateTime> TTS { get; set; }
        public string TT { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> RunningTotal { get; set; }
        public string Declaration { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
