//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alver.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STOCK
    {
        public int رقم_المادة { get; set; }
        public string اسم_المادة { get; set; }
        public Nullable<decimal> عدد_الكروزات_المتوفرة { get; set; }
        public Nullable<int> العملة { get; set; }
        public Nullable<decimal> سعر_شراء_الواحدة { get; set; }
        public Nullable<decimal> تكلفة_الشراء { get; set; }
        public Nullable<decimal> سعر_مبيع_الواحدة { get; set; }
        public Nullable<decimal> مجموع_المبيعات { get; set; }
        public Nullable<decimal> هامش_الربح_في_القطعة_الواحدة { get; set; }
        public Nullable<decimal> الربح_المتوقع { get; set; }
    }
}
