//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alver.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyBulletin
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> RateDate { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> ReversedRate { get; set; }
        public Nullable<bool> TOUSD { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
    
        public virtual Currency Currency { get; set; }
    }
}
