//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alver.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeFund
    {
        public int Id { get; set; }
        public Nullable<bool> ExchangeType { get; set; }
        public Nullable<System.DateTime> ExchangeDate { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> AccountFromId { get; set; }
        public Nullable<int> AccountFundFromId { get; set; }
        public Nullable<int> AccountToId { get; set; }
        public Nullable<int> AccountFundToId { get; set; }
        public Nullable<decimal> FromAmount { get; set; }
        public Nullable<bool> Factor { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> ToAmount { get; set; }
        public string Declaration { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<bool> PROTECTED { get; set; }
    
        public virtual AccountFund AccountFund { get; set; }
        public virtual AccountFund AccountFund1 { get; set; }
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual User User { get; set; }
    }
}
