//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alver.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public Nullable<int> ItemUnitId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<System.DateTime> LUD { get; set; }
        public Nullable<bool> PROTECTED { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual ItemUnit ItemUnit { get; set; }
    }
}
