//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alver.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CLIENTS
    {
        public int AccountId { get; set; }
        public string Account { get; set; }
        public Nullable<decimal> USDAmount { get; set; }
        public Nullable<decimal> SYPAmount { get; set; }
        public Nullable<decimal> TLAmount { get; set; }
        public Nullable<decimal> EUROAmount { get; set; }
        public Nullable<decimal> SARAmount { get; set; }
        public Nullable<decimal> GRAND { get; set; }
    }
}
